---
driver:
  name: vagrant

verifier:
  name: serverspec
  default_pattern: true

provisioner:
  name: ansible_playbook
  hosts: localhost
  ansible_cfg_path: test/ansible.cfg
  require_chef_for_busser: false
  require_ruby_for_busser: false
  ansible_host_key_checking: false
  additional_copy_role_path:
    - test/roles/geerlingguy.java

platforms:
  - name: centos-7.2

suites:
  - name: default
    provisioner:
      hosts: all
      name: ansible_playbook
      playbook: test/integration/default/test.yml
      additional_copy_path:
        - "."
